MeCRISPR/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^$', 'crispr.views.cassette_search_form', name='home'),
    url(r'^search$', 'crispr.views.cassette_search_results', name='search'),
    url(r'^blast$', 'crispr.views.blast_search', name='blast'),
    url(r'^blast/(?P<blast_id>\w+)$', 'crispr.views.blast_result',
        name='blast_result'),
    url(r'^hmmscan$', 'crispr.views.hmmscan_search', name='hmmscan'),
    url(r'^hmmscan/(?P<hmmscan_id>\w+)$', 'crispr.views.hmmscan_result',
        name='hmmscan_result'),
    url(r'^cassette/(?P<cassette_accession>\w+).fasta$',
        'crispr.views.cassette_fasta', name='fasta'),
    url(r'^spacer_blast/(?P<spacer_id>\w+)$',
        'crispr.views.spacer_blast_hits', name='spacer_blast'),
    url(r'^contig/(?P<contig_accession>[-|.\w]+).svg$',
        'crispr.views.contig_image', name='contig_image'),
    url(r'^contig/(?P<contig_accession>[-|.\w]+)$',
        'crispr.views.show_contig', name='contig'),
    url(r'^contig/fasta/(?P<contig_accession>[-|.\w]+).fasta$',
        'crispr.views.contig_fasta', name='contig_fasta'),
    url(r'^methods/$', 'crispr.views.list_methods',
        name='methods'),
    url(r'^metagenomes/$', 'crispr.views.list_metagenomes',
        name='metagenomes'),
    url(r'^about/$', 'django.contrib.flatpages.views.flatpage',
        {'url': '/about/'}, name='about'),
    url(r'^help/$', 'django.contrib.flatpages.views.flatpage',
        {'url': '/help/'}, name='help'),

    # url(r'^MeCRISPR/', include('MeCRISPR.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

crispr/models.py
from django.db import models
from django.core.validators import MaxLengthValidator

import tasks


def identity_string(seq1, seq2):
    l = ['|' if seq1[i] == seq2[i] else ' '
         for i in xrange(len(seq1))]
    return ''.join(l)


class Metagenome(models.Model):
    name = models.CharField(max_length=250)
    accession = models.CharField(max_length=250, unique=True)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)
    reference = models.TextField(blank=True)

    def __unicode__(self):
        return self.name


class Method(models.Model):
    name = models.CharField(max_length=250)
    accession = models.CharField(max_length=250, unique=True)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)
    reference = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['accession', 'name']


class Contig(models.Model):
    accession = models.CharField(max_length=250, unique=True)
    length = models.IntegerField()
    cas_hit = models.BooleanField()
    metagenome = models.ForeignKey(Metagenome)
    taxonomy = models.TextField(blank=True)
    sequence = models.TextField(blank=True)

    methods = models.ManyToManyField(Method, through='Cassette')

    def __unicode__(self):
        return '<Contig %s>' % self.accession

    def taxnl(self):
        if self.taxonomy:
            return self.taxonomy.replace('; ', '\n')


class RepeatCluster(models.Model):
    def __unicode__(self):
        return '<RepeatCluster %d>' % self.id


class RepeatCrisprDB(models.Model):
    repeat_sequence = models.CharField(max_length=100, unique=True)
    taxid = models.IntegerField()
    name = models.TextField()

    def __unicode__(self):
        return '<RepeatCrisprDB %s>' % self.name


class Cassette(models.Model):
    STRAND = (
        ('+', 'Forward'),
        ('-', 'Reverse'))

    ACTIVE = 'A'
    OUTDATED = 'O'
    DELETED = 'D'
    STATUS = (
        (ACTIVE, 'Active'),
        (OUTDATED, 'Outdated'),
        (DELETED, 'Deleted'))

    accession = models.CharField(max_length=16, db_index=True)
    version = models.IntegerField(default=1)
    status = models.CharField(max_length=1, choices=STATUS, default=ACTIVE,
                              db_index=True)
    sequence = models.TextField()
    left_flank = models.TextField()
    right_flank = models.TextField()
    high_quality = models.BooleanField()
    repeat_consensus = models.TextField()
    repeat_cluster = models.ForeignKey(RepeatCluster, blank=True, null=True)
    repeat_crisprdb = models.ForeignKey(RepeatCrisprDB, blank=True, null=True)
    contig = models.ForeignKey(Contig)
    start = models.IntegerField()
    end = models.IntegerField()
    strand = models.CharField(max_length=1, choices=STRAND, blank=True)
    method = models.ForeignKey(Method)

    def __unicode__(self):
        return "<Cassette %s>" % self.accession

    class Meta:
        ordering = ['contig', 'accession']
        unique_together = ('accession', 'version')


class Spacer(models.Model):
    cassette = models.ForeignKey(Cassette)
    position = models.IntegerField()
    sequence = models.TextField()

    def __unicode__(self):
        return "<Spacer %s/%s>" % (
            self.cassette.accession,
            self.position)

    def has_phagehits(self):
        return self.phagehit_set.count() > 0

    def length(self):
        return len(self.sequence.replace('-', ''))

    class Meta:
        unique_together = ('cassette', 'position')
        ordering = ['cassette', 'position']


class Repeat(models.Model):
    cassette = models.ForeignKey(Cassette)
    position = models.IntegerField()
    sequence = models.TextField()

    def length(self):
        return len(self.sequence.replace('-', ''))

    def __unicode__(self):
        return "<Repeat %s/%s>" % (self.cassette.accession,
                                   self.position)

    class Meta:
        unique_together = ('cassette', 'position')
        ordering = ['cassette', 'position']


class PhageHit(models.Model):
    spacer = models.ForeignKey(Spacer)
    hit_description = models.CharField(max_length=500)
    hit_accession = models.CharField(max_length=100)
    evalue = models.FloatField()
    query = models.CharField(max_length=100)
    hit = models.CharField(max_length=100)

    def identity(self):
        return identity_string(self.query, self.hit)

    class Meta:
        ordering = ['evalue']


class Deferred(models.Model):
    QUEUE = 'q'
    RUNNING = 'r'
    COMPLETE = 'c'
    FAILED = 'f'
    STATUS_CHOICES = (
        (QUEUE, 'in queue'),
        (RUNNING, 'running'),
        (COMPLETE, 'complete'),
        (FAILED, 'failed'),
    )

    status = models.CharField(choices=STATUS_CHOICES,
                              max_length=1,
                              default=QUEUE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Blast(Deferred):
    BLASTN = 'blastn'
    TBLASTN = 'tblastn'
    PROGRAM_CHOICES = (
        (BLASTN, 'blastn, nucleotide query'),
        (TBLASTN, 'tblastn, protein query'),
    )

    SPACERS = 'spacers'
    REPEATS = 'repeats'
    CONTIGS = 'contigs'
    DB_CHOICES = (
        (SPACERS, 'spacers'),
        (REPEATS, 'repeats'),
        (CONTIGS, 'contigs'),
    )

    query = models.TextField(validators=[MaxLengthValidator(8192)],
                             help_text='Raw or FASTA sequence')
    result = models.TextField(blank=True)
    truncated = models.BooleanField(default=False)
    program = models.CharField(
        choices=PROGRAM_CHOICES,
        max_length=16,
        default=BLASTN)
    evalue = models.FloatField('E-value', default=0.01)
    short = models.BooleanField(
        'correction for short queries (<30nt)')
    database = models.CharField(
        choices=DB_CHOICES,
        max_length=16,
        default=CONTIGS)


    def run(self):
        tasks.blast.delay(self.id)

    def __unicode__(self):
        return "<Blast %s %s>" % (self.created.strftime('%d-%m-%y %H:%M'),
                                  self.status.upper())


class BlastHit(models.Model):
    blast = models.ForeignKey(Blast)
    query_id = models.CharField(max_length=250)
    query_length = models.IntegerField()
    query_start = models.IntegerField()
    query_end = models.IntegerField()
    query_sequence = models.TextField()
    subject_id = models.CharField(max_length=250)
    subject_length = models.IntegerField()
    subject_start = models.IntegerField()
    subject_end = models.IntegerField()
    subject_sequence = models.TextField()
    percent_identity = models.FloatField()
    identity_count = models.IntegerField()
    alignment_length = models.IntegerField()
    mismatches = models.IntegerField()
    gap_opens = models.IntegerField()
    bit_score = models.FloatField()
    score = models.IntegerField()
    evalue = models.FloatField()

    def identity(self):
        return identity_string(self.query_sequence,
                               self.subject_sequence)

    def subseq(self, max_length=80):
        idn = self.identity()
        query_strand = 1 if self.query_start <= self.query_end else -1
        subject_strand = 1 if self.subject_start <= self.subject_end else -1
        for i in xrange(0, len(self.query_sequence), max_length):
            j = min(i + max_length, len(self.query_sequence))
            q_s = self.query_start + query_strand * i
            q_e = self.query_start + query_strand * (j - 1)
            s_s = self.subject_start + subject_strand * i
            s_e = self.subject_start + subject_strand * (j - 1)

            d = {'query_sequence': self.query_sequence[i:j],
                 'query_start': q_s,
                 'query_end': q_e,
                 'subject_sequence': self.subject_sequence[i:j],
                 'subject_start': s_s,
                 'subject_end': s_e,
                 'identity': idn[i:j],
                 }
            yield d

    class Meta:
        ordering = ['pk']


class HmmScan(Deferred):
    query = models.TextField(validators=[MaxLengthValidator(8192)],
                             help_text='Raw or FASTA sequence')
    result = models.TextField(blank=True)

    def run(self):
        tasks.hmmscan.delay(self.id)

    def __unicode__(self):
        return "<HmmScan %s %s>" % (self.created.strftime('%d-%m-%y %H:%M'),
                                    self.status.upper())

crispr/forms.py
from django import forms
from django.utils.safestring import mark_safe

from models import Method, Blast, HmmScan, Metagenome


ACCESSION_EXAMPLE = 'MC_0001852.1'
CONTIG_ACCESSION_EXAMPLE = 'GOS|JCVI_SCAF_1096627147282'


class CassetteSearchForm(forms.Form):
    METHOD_CHOICES = (
        ('A', 'Any'),
        ('F', 'Found'),
        ('N', 'Not found'),
    )

    accession = forms.CharField(max_length=250, required=False,
                                widget=forms.TextInput(
            attrs={'data-example': ACCESSION_EXAMPLE}),
                                help_text=mark_safe(
            'Cassette accession can be specified as <code>MC_NNNNNNN</code> or '
            '<code>MC_NNNNNNN.VERSION</code>'))

    high_quality = forms.BooleanField(label='Only high-quality',
                                      required=False)

    repeat_cluster = forms.IntegerField(required=False,
                                        widget=forms.TextInput(
            attrs={'data-example': '3'}),
                                        help_text='Specify cluster accession')

    contig_accession = forms.CharField(max_length=250, required=False,
                                       widget=forms.TextInput(
            attrs={'data-example': CONTIG_ACCESSION_EXAMPLE}),
                                       help_text='Specify contig accession')

    phage_blast = forms.BooleanField(label='Phage BLAST hits',
                                     required=False)

    metagenome = forms.ModelMultipleChoiceField(queryset=Metagenome.objects.all(),
                                                required=False,
                                                help_text='Use Ctrl+click to select multiple items')

    method = forms.ModelMultipleChoiceField(queryset=Method.objects.all(),
                                            required=False,
                                            help_text='Filter cassettes by prediction methods. '
                                                      'Use Ctrl+click to select multiple items')

    def __init__(self, *args, **kwargs):
        try:
            mq = kwargs['mq']
            del(kwargs['mq'])
        except KeyError:
            mq = Method.objects.all()

        super(CassetteSearchForm, self).__init__(*args, **kwargs)

        for method in mq:
            field_name = 'M_' + method.accession
            self.fields[field_name] = forms.ChoiceField(
                choices=self.METHOD_CHOICES,
                required=False,
                label=method.name,
                initial='A')
            self.fields[field_name].group = ('Filter contigs',
                'You can limit search to contigs having '
                'certain combination of prediction methods')

        for field_name in self.fields:
            try:
                self.fields[field_name].group
            except AttributeError:
                self.fields[field_name].group = ''

    def clean(self):
        cleaned_data = super(CassetteSearchForm, self).clean()

        empty = True

        for field in cleaned_data:
            if cleaned_data[field]:
                empty = False

        if empty == True:
            raise forms.ValidationError("Empty request")

        return cleaned_data

BLAST_QUERY_EXAMPLE = """>sample_spacer
AAAATGATACTTCTGACTTCGTTGTGCGTAA
>sample_repeat
ATCCCTTTTTAGTCAGGGCATTTCTTCGAAC
>sample_piece_of_contig
AGCCTATATTGAATTAAGGTGATCTTCGAGGGTTCTGCCATCACAACTATTCCCTTAACTCCTCTAGCCAACAGGT
"""

class BlastForm(forms.ModelForm):
    class Meta:
        model = Blast
        fields = ['query', 'program', 'evalue',
                  'short', 'database']
        widgets = {
            'query': forms.Textarea(
                attrs={'data-example': BLAST_QUERY_EXAMPLE}
                ),
            }

HMMSCAN_QUERY_EXAMPLE = """>sample_repeat1
GAACTGAGACCCGATCTAAAGGGGATTAAGAC
>sample_repeat2
GCATCGCCCGGCTAAACAGCCGGGCGCGGATTGAAAC
"""

class HmmScanForm(forms.ModelForm):
    class Meta:
        model = HmmScan
        fields = ['query']
        widgets = {
            'query': forms.Textarea(
                attrs={'data-example': HMMSCAN_QUERY_EXAMPLE}
                ),
            }

templates/crispr/cassette_search_results.html
{% extends "base.html" %}

{% load crispr_extras %}

{% block title %}
  {% if cassettes.paginator.count > 0 %}
    Found {{ cassettes.paginator.count }}{% if cassettes.paginator.num_pages > 1 %},
    page {{ current_page }}/{{ cassettes.paginator.num_pages}}
  {% endif %}
  {% else %}
    Nothing found
  {% endif %}
  - Cassette search — MeCRISPR
{% endblock %}

{% block content %}
  <div class="span12">
    <h1>Results</h1>
    {% if cassettes.paginator.count > 0 %}
      <div class="download btn-group">
        <a class="btn" href="{{ request_path }}&amp;format=csv&amp;sep=1"><i class="icon-file"></i> Export Excel CSV</a>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <a href="{{ request_path }}&amp;format=csv">Plain CSV</a>
          </li>
        </ul>
      </div>
      <div class="download btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-file"></i>
            Export FASTA
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ request_path }}&amp;format=repeat_fasta">Repeat consensus</a></li>
            <li><a href="{{ request_path }}&amp;format=spacer_fasta">Spacers</a></li>
            <li><a href="{{ request_path }}&amp;format=contig_fasta">Contigs</a></li>
        </ul>
      </div>
      <p>Found: {{ cassettes.paginator.count }}</p>
      <a href="#" onclick="$('.hide, .mhide').show(); $('.nhide').hide(); return false;" class="dashed nhide">[expand all]</a>
      <a href="#" onclick="$('.hide, .mhide').hide(); $('.nhide').show(); return false;" class="dashed hide">[collapse all]</a>
      <table class="table table-hover">
	<tr>
	  <th>#
	  <th>Accession
	  <th>Contig
	  <th>Method
	  <th>Length
	  <th>Repeats/Spacers
	  <th>High-quality
	</tr>
	{% for cassette in cassettes %}
	  {% ifchanged cassette.contig.accession %}
	    {% cycle "odd" "even" as oddeven silent %}
	  {% endifchanged %}
	  <tr class="{{ oddeven }} start" onclick="$('.cas_{{ cassette.accession }}').toggle()">
	    <td class="nobr">
	      <i class="icon-chevron-right cas_{{ cassette.accession }} nhide"></i>
	      <i class="icon-chevron-down cas_{{ cassette.accession }} mhide" style="display: none"></i>
	      {{ forloop.counter|add:cassettes.start_index|add:-1 }}
            <td>{{ cassette.accession }}
            <td>{{ cassette.contig.accession }}
	    <td><abbr title="{{ cassette.method.name }}">{{ cassette.method.accession }}</span>
            <td>{{ cassette.sequence | length }}
            <td>{{ cassette.repeat_set.all|length }}/{{ cassette.spacer_set.all|length }}
	    <td>{% if cassette.high_quality %}<i class="icon-ok-sign"></i>{% endif %}
          </tr>
	  <tr class="{{ oddeven }} cas_{{ cassette.accession }} hide">
	    <td>
	    <td colspan="2"><h4>left flank</h4>
	    <td colspan="4" class="sequence">{{ cassette.left_flank|wrap_wbr:10 }}
	  </tr>
	  <tr class="{{ oddeven }} cas_{{ cassette.accession }} hide">
	    <td>
	    <td colspan="2">
	      <h4>cassette</h4>
	      <table class="info">
		<tr>
		  <td>full accession
		  <td>{{ cassette.accession }}.{{ cassette.version }}
		</tr>
		<tr>
		  <td>version
		  <td>{{ cassette.version }}
		</tr>
		<tr>
		  <td>start
		  <td>{{ cassette.start }}
		</tr>
		<tr>
		  <td>end
		  <td>{{ cassette.end }}
		</tr>
		{% if cassette.strand %}
		  <tr>
		    <td>strand
		    <td>{{ cassette.strand }}
		  </tr>
		{% endif %}
	      </table>
	      <a href="{% url 'fasta' cassette.accession %}">[fasta]</a>

	      <h4>contig</h4>
	      <table class="info">
		<tr>
		  <td>metagenome
		  <td>
		    <a href="{{ cassette.contig.metagenome.url }}">
		      <abbr title="{{ cassette.contig.metagenome.name }}">{{ cassette.contig.metagenome.accession }}</abbr>
		    </a>
		</tr>
		<tr>
		  <td>accession
		  <td><a href="{% url 'contig' cassette.contig.accession %}">{{ cassette.contig.accession }}</a>
		</tr>
		<tr>
		  <td>length
		  <td>{{ cassette.contig.length }}
		</tr>
		{% if cassette.contig.taxonomy %}
		  <tr>
		    <td>taxonomy
		    <td>{{ cassette.contig.taxnl|linebreaks }}
		  </tr>
		{% endif %}
	      </table>
          {% if cassette.contig.cas_hit %}
	    <span class="label"><abbr title="Flanking sequences has blastx hits to CAS-genes">CAS blastx hit</abbr></span><br/>
          {% endif %}
          <a href="{% url 'contig_fasta' cassette.contig.accession %}">[fasta]</a>
	    <td colspan="2" class="nobr auto-scroll">
	      <h4>repeats</h4>
	      <div class="sequence">
		{% for repeat in cassette.repeat_set.all %}{{ repeat.position|stringformat:"02d" }}: {{ repeat.sequence }}<br/>{% endfor %}
	      </div>
	      <h4>repeat consensus</h4>
	      <div class="sequence">
		&nbsp;&nbsp;&nbsp;&nbsp;{{ cassette.repeat_consensus }}
		{% if cassette.repeat_cluster %}
		  <a href="{% url 'search' %}?repeat_cluster={{ cassette.repeat_cluster.id }}" class="cluster">
		    [cluster #{{ cassette.repeat_cluster.id }}]
		  </a>
		{% endif %}
	      </div>
		{% with dr=cassette.repeat_crisprdb %}
		  {% if dr %}
		    <div class="crisprdb">
		      <span class="label">
			<abbr title="Repeat sequence found in CRISPRdb">CRISPRdb</abbr>
		      </span>
		      <a href="http://crispr.u-psud.fr/crispr/samecrispr.php?drseq={{ dr.repeat_sequence}}">{{ dr.name }}</a>
		    </div>
		  {% endif %}
		{% endwith %}
	    <td colspan="3" class="nobr auto-scroll"><h4>spacers</h4>
	      <div class="sequence">
		{% for spacer in cassette.spacer_set.all %}
		  {{ spacer.position|stringformat:"02d" }}:
		  {% if spacer.has_phagehits %}
		    <abbr class="phage" title="{{ spacer.phagehit_set.all.0.hit_description }}">{{ spacer.sequence }}</abbr>
		    <a href="{% url "spacer_blast" spacer.pk %}">phage blast</a>
		  {% else %}
		    {{ spacer.sequence }}
		  {% endif %}
		  <br/>
		{% endfor %}
	      </div>
	  </tr>
	  <tr class="{{ oddeven }} cas_{{ cassette.accession }} hide">
	    <td>
	    <td colspan="2"><h4>right flank</h4>
	    <td colspan="4" class="sequence">{{ cassette.right_flank|wrap_wbr:10 }}
	  </tr>
	{% endfor %}
      </table>
    {% else %}
      <h2>Nothing found.</h2>
      {% include "crispr/cassette_search_form.html" %}
    {% endif %}

    <div class="pagination">
      <ul>
	{% if cassettes.has_previous %}
	  <li><a href="{% replace_query_param url "page" cassettes.previous_page_number %}">←</a></li>
	{% endif %}
	{% for page in pages %}
	  {% if page != 0 %}
	    <li {% if page == current_page %}class="disabled"{% endif %}>
	      <a href="{% replace_query_param url "page" page %}">{{ page }}</a>
	    </li>
	  {% else %}
	    <li class="disabled">
	      <a href="">…</a>
	    </li>
	  {% endif %}
	{% endfor %}
	{% if cassettes.has_next %}
	  <li><a href="{% replace_query_param url "page" cassettes.next_page_number %}">→</a></li>
	{% endif %}
      </ul>
    </div>
  </div>
{% endblock %}

templates/crispr/show_contig.html
{% extends "base.html" %}

{% load crispr_extras %}

{% block title %}Contig {{ contig.accession }} - MeCRISPR{% endblock %}

{% block content %}
  <div class="span12">
    <h2>Contig {{ contig.accession }}</h2>

    <table class="info">
      <tr>
	<td>metagenome
	<td>
	  <a href="{{ contig.metagenome.url }}">
	    <abbr title="{{ contig.metagenome.name }}">{{ contig.metagenome.accession }}</abbr>
	  </a>
      </tr>
      <tr>
	<td>length
	<td>{{ contig.length }}
      </tr>
      {% if contig.taxonomy %}
	<tr>
	  <td>taxonomy
	  <td>{{ contig.taxnl|linebreaks }}
	</tr>
      {% endif %}
      {% if cassettes %}
	<tr>
	  <td>cassette predictions
	  <td>{{ cassettes|length }}
	</tr>
      {% endif %}
    </table>
    {% if contig.cas_hit %}
      <span class="label"><abbr title="Flanking sequences has blastx hits to CAS-genes">CAS blastx hit</abbr></span><br/>
    {% endif %}
    <a href="{% url 'contig_fasta' contig.accession %}">[fasta]</a>

    <h2>Plot</h2>
    <embed src="{% url 'contig_image' contig.accession %}" type="image/svg+xml" />

    <h2>Cassettes</h2>
    <table class="table table-hover">
      <tr>
	<th>Accession
	<th>Method
	<th>Length
	<th>Repeats/Spacers
	<th>High-quality
      </tr>
      {% for cassette in cassettes %}
	<tr class="{% cycle "odd" "even" %} start">
          <td>{{ cassette.accession }}
	  <td><abbr title="{{ cassette.method.name }}">{{ cassette.method.accession }}</span>
          <td>{{ cassette.sequence | length }}
          <td>{{ cassette.repeat_set.all|length }}/{{ cassette.spacer_set.all|length }}
	  <td>{% if cassette.high_quality %}<i class="icon-ok-sign"></i>{% endif %}
        </tr>
        <tr class="{% cycle "odd" "even" %} cas_{{ cassette.accession }}">
	  <td colspan="1"><h4>left flank</h4>
	  <td colspan="4" class="sequence">{{ cassette.left_flank|wrap_wbr:10 }}
	</tr>
        <tr class="{% cycle "odd" "even" %} cas_{{ cassette.accession }}">
	  <td>
	    <h4>cassette</h4>
	    <table class="info">
	      <tr>
		<td>full accession
		<td>{{ cassette.accession }}.{{ cassette.version }}
	      </tr>
	      <tr>
		<td>version
		<td>{{ cassette.version }}
	      </tr>
	      <tr>
		<td>start
		<td>{{ cassette.start }}
	      </tr>
	      <tr>
		<td>end
		<td>{{ cassette.end }}
	      </tr>
	      {% if cassette.strand %}
		<tr>
		  <td>strand
		  <td>{{ cassette.strand }}
		</tr>
	      {% endif %}
	    </table>
	    <a href="{% url 'fasta' cassette.accession %}">[fasta]</a>

	  </td>
	  <td colspan="2" class="nobr auto-scroll">
	    <h4>repeats</h4>
	    <div class="sequence">
	      {% for repeat in cassette.repeat_set.all %}{{ repeat.position|stringformat:"02d" }}: {{ repeat.sequence }}<br/>{% endfor %}
	    </div>
	    <h4>repeat consensus</h4>
	    <div class="sequence">
	      &nbsp;&nbsp;&nbsp;&nbsp;{{ cassette.repeat_consensus }}
	      {% if cassette.repeat_cluster %}
		<a href="{% url 'search' %}?repeat_cluster={{ cassette.repeat_cluster.id }}" class="cluster">
		  [cluster #{{ cassette.repeat_cluster.id }}]
		</a>
	      {% endif %}
	    </div>
	    {% with dr=cassette.repeat_crisprdb %}
	      {% if dr %}
	        <div class="crisprdb">
	          <span class="label">
		    <abbr title="Repeat sequence found in CRISPRdb">CRISPRdb</abbr>
		  </span>
		  <a href="http://crispr.u-psud.fr/crispr/samecrispr.php?drseq={{ dr.repeat_sequence}}">{{ dr.name }}</a>
		</div>
	      {% endif %}
	    {% endwith %}
	  </td>
	  <td colspan="2" class="nobr auto-scroll"><h4>spacers</h4>
	    <div class="sequence">
	      {% for spacer in cassette.spacer_set.all %}
		{{ spacer.position|stringformat:"02d" }}:
		{% if spacer.has_phagehits %}
		  <abbr class="phage" title="{{ spacer.phagehit_set.all.0.hit_description }}">{{ spacer.sequence }}</abbr>
		  <a href="{% url "spacer_blast" spacer.pk %}">phage blast</a>
		{% else %}
		  {{ spacer.sequence }}
		{% endif %}
		<br/>
	      {% endfor %}
	    </div>
	  </td>
	</tr>
        <tr class="{% cycle "odd" "even" %} cas_{{ cassette.accession }}">
	  <td colspan="1"><h4>right flank</h4>
	  <td colspan="4" class="sequence">{{ cassette.right_flank|wrap_wbr:10 }}
	</tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}